name: Check
on: [push, pull_request]
jobs:
    pipeline:
        name: CI pipeline
        runs-on: ubuntu-latest
        env:
            GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
            GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GRADLE_ENTERPRISE_CACHE_USERNAME }}
            GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD }}
        steps:
            - uses: actions/checkout@v2
            - name: Set up JDK 17
              uses: actions/setup-java@v2
              with:
                  java-version: '17'
                  distribution: 'adopt'
            - name: Run Gradle build
              uses: gradle/gradle-build-action@v2
              with:
                  arguments: clean assemble -Dscan.tag.exp5
